const lifeTrackerSayings = <String>[
  'Small steps become a life you are proud of.',
  'Keep the promise you made to yourself today.',
  'Progress grows where attention goes.',
  'A clear next step is stronger than a perfect plan.',
  'Start gently. Continue steadily.',
  'Your future is shaped by ordinary days.',
  'Do the next useful thing.',
  'Consistency makes difficult things familiar.',
  'A little progress still changes the path.',
  'Build the day you want to remember.',
  'You do not need to rush to keep moving.',
  'Make today easier for tomorrow.',
  'A finished small task creates real momentum.',
  'Return to what matters, one step at a time.',
  'Quiet effort still counts.',
  'Choose progress you can repeat.',
  'The next step does not need to be large.',
  'Your direction matters more than your speed.',
  'Make room for the person you are becoming.',
  'A simple plan leaves energy for the work.',
  'Begin before confidence arrives.',
  'Let your actions make the decision real.',
  'A steady pace can carry a heavy goal.',
  'Today is part of the result.',
  'Protect time for what you say matters.',
  'One honest update is better than a perfect record.',
  'Notice what worked, then use it again.',
  'Your effort deserves a clear place to go.',
  'Make the useful choice easier to repeat.',
  'Good systems support you on difficult days.',
  'You can pause without giving up.',
  'Clarity turns pressure into action.',
  'A goal becomes real through today’s action.',
  'Keep moving, even when the step is small.',
  'Finishing teaches you how to begin again.',
  'You are allowed to adjust the plan.',
  'Track the truth, not a perfect story.',
  'What you repeat becomes easier to trust.',
  'Use your energy where it matters most.',
  'A calm plan can still be ambitious.',
  'Focus on the work in front of you.',
  'The smallest useful action breaks the stall.',
  'Progress is evidence that change is possible.',
  'Make fewer promises and keep them well.',
  'Leave space for life, then keep going.',
  'Your pace can change without changing your purpose.',
  'Do enough today to help tomorrow begin.',
  'Plans serve people, not the other way around.',
  'A clear boundary protects meaningful work.',
  'Success is often a collection of ordinary finishes.',
  'Your record can teach you without judging you.',
  'Improve the system when effort alone is not enough.',
  'A missed day is information, not a verdict.',
  'Make the next choice visible.',
  'Repeat what brings you closer.',
  'Build momentum with something you can finish.',
  'Your attention is part of your plan.',
  'A useful routine should make life lighter.',
  'Progress can be quiet and still be real.',
  'Choose the step that reduces tomorrow’s friction.',
  'The work counts even before the result shows.',
  'Let today be practical, not perfect.',
  'A goal needs a place in your day.',
  'Celebrate completion, then learn from it.',
  'You can simplify without lowering the goal.',
  'Make your plan fit your actual life.',
  'A better direction begins with one honest choice.',
  'Give important work a real time and place.',
  'Your best pace is one you can sustain.',
  'Use what happened today to plan tomorrow wisely.',
  'Good progress leaves room to breathe.',
  'Start with what is clear.',
  'A consistent hour can reshape a year.',
  'The next version of you is built in the present.',
  'Keep the goal large and the next action simple.',
  'A calm restart is still a restart.',
  'Completion creates confidence.',
  'You can learn from every attempt.',
  'Put effort where it can become a result.',
  'One deliberate day is never wasted.',
  'Let your schedule reflect your priorities.',
  'Make progress easy to see and easy to continue.',
  'The plan can bend while the purpose stays firm.',
  'Use small wins to carry bigger work.',
  'Today’s action is tomorrow’s starting point.',
  'Give yourself a next step, not more pressure.',
  'A useful reminder returns you to your intention.',
  'Work with your life, not against it.',
  'The right amount of structure creates freedom.',
  'Do what matters before adding more.',
  'Your progress deserves patience and honesty.',
  'Keep what helps. Change what does not.',
  'A thoughtful pause can protect the goal.',
  'Make the path clearer each time you walk it.',
  'A strong day begins with a simple priority.',
  'Effort becomes progress when it has direction.',
  'Finish one thing and let that be enough to begin.',
  'Your goals should help you live, not crowd your life.',
  'The life you want is built through choices you repeat.',
  'Move forward with purpose and leave room for grace.',
];

String sayingForDay(DateTime day) {
  final start = DateTime(day.year, 1, 1);
  return lifeTrackerSayings[day.difference(start).inDays %
      lifeTrackerSayings.length];
}
